"use client";
import Image from "next/image";import {useCallback,useEffect,useState} from "react";
type Logical={logical_region_id:string;source_fragment_ids:number[];bbox:number[];region_type:string};
type Item={review_id:string;page_order:number;state:string;logical_regions:Logical[];ordered_region_ids:string[];excluded_region_ids:string[];human_transcriptions:Record<string,string>;image_dimensions:{width:number;height:number}|null;image_url:string|null};
type Queue={total_pages:number;completed_pages:number;remaining_pages:number;representation_confirmation_required:boolean;legacy_fragment_gt_incompatible:boolean;prior_hierarchical_gt_incompatible:boolean;ocr_samples_preserved:number;completed_ocr_gt_regions:number;remaining_ocr_gt_regions:number;logical_text_corrections:number;items:Item[];model_calls:{vlm:number;ollama:number}};const API="http://127.0.0.1:8000";
export default function ReaderCorrectnessReview({projectId}:{projectId:string}){
 const [queue,setQueue]=useState<Queue|null>(null),[pageIndex,setPageIndex]=useState(0),[ordered,setOrdered]=useState<string[]>([]),[excluded,setExcluded]=useState<string[]>([]),[selected,setSelected]=useState<string|null>(null),[text,setText]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{const r=await fetch(`${API}/projects/${projectId}/reader-logical-review`,{cache:"no-store"});if(!r.ok)throw new Error("Không thể tải trang kiểm tra");setQueue(await r.json())},[projectId]);useEffect(()=>{
  // Queue loading is the external synchronization performed by this effect.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  void load().catch(e=>setError(String(e)))
 },[load]);const item=queue?.items[pageIndex];useEffect(()=>{if(!item)return;
  // Restore only persisted click-order work for this source/revision.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  setOrdered(item.ordered_region_ids);setExcluded(item.excluded_region_ids);setSelected(null);setText("")
 },[item]);
 async function persist(nextOrdered:string[],nextExcluded:string[],verified=false){if(!item)return false;setSaving(true);setError("");try{const r=await fetch(`${API}/projects/${projectId}/reader-logical-review/${item.review_id}/order`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ordered_region_ids:nextOrdered,excluded_region_ids:nextExcluded,verified})});if(!r.ok)throw new Error((await r.json()).detail);setOrdered(nextOrdered);setExcluded(nextExcluded);if(verified)await load();return true}catch(e){setError(String(e));return false}finally{setSaving(false)}}
 function selectRegion(id:string){setSelected(id);setText(item?.human_transcriptions[id]??"");if(!ordered.includes(id)&&!excluded.includes(id))void persist([...ordered,id],excluded)}
 function undo(){if(!ordered.length)return;const removed=ordered[ordered.length-1];void persist(ordered.slice(0,-1),excluded);if(selected===removed)setSelected(null)}
 function reset(){void persist([],excluded);setSelected(null);setText("")}
 function toggleExcluded(){if(!selected)return;if(excluded.includes(selected)){void persist(ordered,[...excluded.filter(id=>id!==selected)]);return}void persist(ordered.filter(id=>id!==selected),[...excluded,selected])}
 async function saveText(){if(!item||!selected||!text.trim())return;setSaving(true);setError("");try{const r=await fetch(`${API}/projects/${projectId}/reader-logical-review/${item.review_id}/logical-regions/${selected}/transcription`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})});if(!r.ok)throw new Error((await r.json()).detail);await load();setSelected(selected)}catch(e){setError(String(e))}finally{setSaving(false)}}
 if(!queue||!item||!item.image_dimensions)return <div className="p-8 text-white/50">Đang tải… {error}</div>;const dims=item.image_dimensions,unresolved=item.logical_regions.length-ordered.length-excluded.length,current=selected?item.logical_regions.find(r=>r.logical_region_id===selected):null;
 const label=(id:string)=>item.human_transcriptions[id]||"Câu chưa có bản chép của người dùng";
 return <section className="mx-auto max-w-[1600px] p-5"><div className="mb-4 flex flex-wrap justify-between gap-3"><div><p className="text-xs uppercase text-violet-300">HUMAN TESTING REQUIRED</p><h2 className="text-xl">Trang {pageIndex+1}/{queue.total_pages} · Page order {item.page_order}</h2><p className="text-sm text-white/55">Hãy bấm trực tiếp các câu theo thứ tự bạn đọc. Còn {unresolved} câu chưa xử lý.</p>{queue.prior_hierarchical_gt_incompatible&&<p className="mt-1 text-xs text-amber-300">Bản xác nhận từ giao diện cũ vẫn được giữ riêng và không được chuyển sang thứ tự mới.</p>}</div><div className="text-right text-xs text-white/45"><p>{queue.completed_pages} trang hoàn tất · {queue.remaining_pages} trang còn lại</p><p>{ordered.length} đã xếp thứ tự · {excluded.length} không cần đọc</p></div></div>
 <div className="grid items-start gap-5 lg:grid-cols-[minmax(0,2fr)_minmax(360px,1fr)]"><div className="rounded-xl border border-white/10 bg-black/40 p-3"><div className="relative w-full" style={{aspectRatio:`${dims.width}/${dims.height}`}}><Image src={item.image_url!} alt="Trang truyện đại diện" fill unoptimized className="object-contain"/>{item.logical_regions.map(r=>{const [x1,y1,x2,y2]=r.bbox,n=ordered.indexOf(r.logical_region_id)+1,isExcluded=excluded.includes(r.logical_region_id),isSelected=selected===r.logical_region_id;return <button key={r.logical_region_id} onClick={()=>selectRegion(r.logical_region_id)} aria-label={n?`Câu thứ ${n}`:isExcluded?"Câu không cần đọc":"Câu chưa chọn"} className={`absolute border-2 transition ${isSelected?"z-20 border-white ring-4 ring-violet-400":"z-10"} ${isExcluded?"border-slate-400 bg-black/65 opacity-60":n?"border-emerald-300 bg-emerald-400/15":"border-amber-300 bg-amber-300/10 hover:bg-amber-300/25"}`} style={{left:`${x1/dims.width*100}%`,top:`${y1/dims.height*100}%`,width:`${(x2-x1)/dims.width*100}%`,height:`${(y2-y1)/dims.height*100}%`}}>{n>0&&<span className="absolute -left-3 -top-4 grid h-8 w-8 place-items-center rounded-full bg-emerald-500 text-lg font-bold text-black">{n}</span>}{isExcluded&&<span className="absolute left-1 top-1 rounded bg-black px-2 py-1 text-[10px] text-white">KHÔNG ĐỌC</span>}</button>})}</div></div>
 <aside className="space-y-4 lg:sticky lg:top-5"><div className="rounded-xl border border-white/10 bg-[#111114] p-4"><h3 className="font-semibold">Câu đang chọn</h3>{current?<><div className="mt-3 grid min-h-40 place-items-center rounded bg-white p-3"><Image unoptimized width={800} height={400} src={`${API}/projects/${projectId}/reader-logical-review/${item.review_id}/logical-regions/${current.logical_region_id}/crop`} alt="Ảnh cắt của câu đang chọn" className="max-h-48 w-auto max-w-full object-contain"/></div><label className="mt-3 block text-sm">Văn bản đúng:</label><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Tự nhập chính xác chữ nhìn thấy…" className="mt-1 h-24 w-full rounded bg-black/40 p-3"/><p className="mt-2 text-sm">Thứ tự đọc: {ordered.includes(current.logical_region_id)?<b className="text-emerald-300">#{ordered.indexOf(current.logical_region_id)+1}</b>:excluded.includes(current.logical_region_id)?<b className="text-slate-300">Không cần đọc</b>:<b className="text-amber-300">Chưa chọn</b>}</p><button disabled={saving||!text.trim()} onClick={()=>void saveText()} className="mt-3 w-full rounded bg-emerald-600 py-2 font-semibold disabled:opacity-30">Lưu chữ</button><button disabled={saving} onClick={toggleExcluded} className="mt-2 w-full rounded border border-white/15 py-2">{excluded.includes(current.logical_region_id)?"Hoàn tác — cần đọc câu này":"Câu này không cần đọc"}</button></>:<p className="mt-3 text-sm text-white/45">Bấm một câu trên trang truyện để xem crop, sửa chữ hoặc loại khỏi thứ tự đọc.</p>}</div>{error&&<p className="rounded bg-red-500/10 p-3 text-sm text-red-300">{error}</p>}</aside></div>
 <div className="mt-5 rounded-xl border border-white/10 bg-[#111114] p-4"><h3 className="font-semibold">Thứ tự đọc hiện tại</h3><ol className="mt-2 grid gap-2 md:grid-cols-2">{ordered.map((id,i)=><li key={id} className="rounded bg-black/30 p-2 text-sm"><b className="mr-2 text-emerald-300">{i+1}.</b>{label(id)}</li>)}</ol>{excluded.length>0&&<div className="mt-3"><p className="text-sm text-white/45">Không cần đọc:</p>{excluded.map(id=><p key={id} className="text-sm text-white/55">– {label(id)}</p>)}</div>}<div className="mt-4 flex flex-wrap gap-2"><button disabled={!ordered.length||saving} onClick={undo} className="rounded border border-white/15 px-4 py-2 disabled:opacity-30">Hoàn tác bước cuối</button><button disabled={!ordered.length||saving} onClick={reset} className="rounded border border-white/15 px-4 py-2 disabled:opacity-30">Đặt lại thứ tự</button><button disabled={unresolved>0||saving} onClick={()=>void persist(ordered,excluded,true)} className="ml-auto rounded bg-violet-500 px-5 py-2 font-semibold disabled:opacity-30">✓ Xác nhận trang này</button></div><div className="mt-4 flex justify-between border-t border-white/10 pt-4"><button disabled={pageIndex===0} onClick={()=>setPageIndex(v=>v-1)}>← Trang trước</button><button disabled={pageIndex===queue.items.length-1} onClick={()=>setPageIndex(v=>v+1)}>Trang tiếp →</button></div></div></section>
}
